### ISSUE TITLE
Pressing Enter for doing the operation.

### ISSUE THREAD

**Issue by ZussM4n** [1289-abhi/Currency_converter#1]
Hi 1289-abhi.

I think it could be a good idea adding the function of pressing Enter for doing the operation of the converter.
I will investigate your code to see what i can do if you want to.
Please answer my request.

See you, and really nice program. :)

**Comment by 1289-abhi** [comment]
Hello @ZussM4n !
Glad you looked at my code and yes I am open for suggestions, this code can be improved in many ways and I will update it as per your suggestions.
Thank you ;)

**Comment by 1289-abhi** [comment]
@ZussM4n , I think the issue can be considered as solved. Thank you for your contribution.
